project_id        = "nzaa-mkt-guid" 
ga4_project_id    = "nzaa-datasets"
environment       = "staging"
ga4_dataset       = "analytics_291449711"
service_account_email = "guid-service-account@nzaa-mkt-guid.iam.gserviceaccount.com"
region            = "australia-southeast1"